# Generated by Django 4.0.6 on 2022-07-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
