# Generated by Django 4.0.6 on 2022-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUsers', '0004_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='stars',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
